---
title: "Replicating Regressions"
format: pdf
---

```{r}
library(stargazer)
library(Hmisc)
library(plm)
library(lme4)
library(lmtest)
library(scales)
library(MatchIt)
library(Zelig)
library(gridExtra)

library(here)
library(dplyr)
library(readr)
```

```{r}
data <- read_csv(here("clean-and-process",
                      "src",
                      "Replication",
                      "county_data.csv"))
```

```{r}
z.data <- data %>%
	select(fips, state, year, drugs, all_cause, income, county_jail_adm,
	       county_prison_adm, px, education, county_crime, blacks,
	       hispanics, race_other) %>%
	mutate(across(c("income", "county_jail_adm", "county_prison_adm", "px",
	                "education", "county_crime", "blacks", "hispanics",
	                "race_other"),
	              ~scale(.x)[,1]))
```

```{r}
FE <-
    plm(log(drugs) ~ I(-income) + county_jail_adm + county_prison_adm + 
            education + blacks + hispanics + race_other + county_crime + year,
        index = c("fips", "year"),
        model = "within",
        data = z.data)

P <- FE$coefficients[1:8]
SE <- coeftest(FE, vcov = vcovHC(FE, "arellano"))[1:8, 2]
p <- coeftest(FE, vcov = vcovHC(FE, "arellano"))[1:8, 4]
R <- cbind(100*P, 100*SE, p)
colnames(R) <- c("Coefficient", "Standard error", "P-value")
rownames(R) <- c("Household income decline", "County jail admissions rate",
                 "County prison admissions rate", "Fraction high school graduates",
                 "Fraction African Americans", "Fraction Hispanics",
                 "Fraction other ethnicity", "Violent crime rate")
```

```{r, results = "asis"}
stargazer(R, digits = 2, out = "e1.pdf", type = "latex")
```


